// Generic 3-letter country/extra codes used across the 980-card collection.
// These are public ISO/FIFA-style trigrams, not licensed brand assets.
export const NATIONS: { code: string; name: string; flag: string }[] = [
  { code: "ARG", name: "Argentina", flag: "🇦🇷" },
  { code: "AUS", name: "Australia", flag: "🇦🇺" },
  { code: "AUT", name: "Austria", flag: "🇦🇹" },
  { code: "BEL", name: "Belgium", flag: "🇧🇪" },
  { code: "BRA", name: "Brazil", flag: "🇧🇷" },
  { code: "CAN", name: "Canada", flag: "🇨🇦" },
  { code: "CIV", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { code: "COL", name: "Colombia", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rica", flag: "🇨🇷" },
  { code: "CRO", name: "Croatia", flag: "🇭🇷" },
  { code: "DEN", name: "Denmark", flag: "🇩🇰" },
  { code: "ECU", name: "Ecuador", flag: "🇪🇨" },
  { code: "EGY", name: "Egypt", flag: "🇪🇬" },
  { code: "ENG", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { code: "ESP", name: "Spain", flag: "🇪🇸" },
  { code: "FRA", name: "France", flag: "🇫🇷" },
  { code: "GER", name: "Germany", flag: "🇩🇪" },
  { code: "GHA", name: "Ghana", flag: "🇬🇭" },
  { code: "IRN", name: "Iran", flag: "🇮🇷" },
  { code: "ITA", name: "Italy", flag: "🇮🇹" },
  { code: "JPN", name: "Japan", flag: "🇯🇵" },
  { code: "KOR", name: "South Korea", flag: "🇰🇷" },
  { code: "KSA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "MAR", name: "Morocco", flag: "🇲🇦" },
  { code: "MEX", name: "Mexico", flag: "🇲🇽" },
  { code: "NED", name: "Netherlands", flag: "🇳🇱" },
  { code: "NGA", name: "Nigeria", flag: "🇳🇬" },
  { code: "NOR", name: "Norway", flag: "🇳🇴" },
  { code: "NZL", name: "New Zealand", flag: "🇳🇿" },
  { code: "PAN", name: "Panama", flag: "🇵🇦" },
  { code: "PAR", name: "Paraguay", flag: "🇵🇾" },
  { code: "PER", name: "Peru", flag: "🇵🇪" },
  { code: "POL", name: "Poland", flag: "🇵🇱" },
  { code: "POR", name: "Portugal", flag: "🇵🇹" },
  { code: "QAT", name: "Qatar", flag: "🇶🇦" },
  { code: "RSA", name: "South Africa", flag: "🇿🇦" },
  { code: "SCO", name: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "SEN", name: "Senegal", flag: "🇸🇳" },
  { code: "SRB", name: "Serbia", flag: "🇷🇸" },
  { code: "SUI", name: "Switzerland", flag: "🇨🇭" },
  { code: "SWE", name: "Sweden", flag: "🇸🇪" },
  { code: "TUN", name: "Tunisia", flag: "🇹🇳" },
  { code: "TUR", name: "Turkey", flag: "🇹🇷" },
  { code: "UKR", name: "Ukraine", flag: "🇺🇦" },
  { code: "URU", name: "Uruguay", flag: "🇺🇾" },
  { code: "USA", name: "USA", flag: "🇺🇸" },
  { code: "VEN", name: "Venezuela", flag: "🇻🇪" },
  { code: "WAL", name: "Wales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "LEG", name: "Legends", flag: "⭐" },
  { code: "STA", name: "Stadiums", flag: "🏟️" },
  { code: "TRO", name: "Trophies", flag: "🏆" },
];

export const NATION_MAP: Record<string, { name: string; flag: string }> =
  Object.fromEntries(NATIONS.map((n) => [n.code, { name: n.name, flag: n.flag }]));